version: "3.8"
services: 
  golang: 
    container_name: marketGo
    image: golang:1.25
    ports: 
      - 8080:8080
    depends_on:
      - redis
    env_file:
      - .env
    networks:
      - golang_network
  redis:
    container_name: my-redis
    image: redis
    ports: 
      - 6379:6379
    networks:
      - golang_network
networks:
  golang_network:
    name: golang_network